name: Preview Deployment

on:
  pull_request:
    branches: [main]

concurrency:
  group: preview-${{ github.event.number }}
  cancel-in-progress: true

jobs:
  preview:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci --prefer-offline --no-audit

      - name: Run Tests
        run: npm test -- --coverage --watchAll=false

      - name: Build Preview
        run: npm run build
        env:
          VITE_SUPABASE_URL: ${{ secrets.VITE_SUPABASE_URL }}
          VITE_SUPABASE_ANON_KEY: ${{ secrets.VITE_SUPABASE_ANON_KEY }}
          NODE_ENV: production

      - name: Comment on PR
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const path = require('path');

            // Calculate build size
            const getDirectorySize = (dirPath) => {
              let totalSize = 0;
              const files = fs.readdirSync(dirPath, { withFileTypes: true });
              
              for (const file of files) {
                const filePath = path.join(dirPath, file.name);
                if (file.isDirectory()) {
                  totalSize += getDirectorySize(filePath);
                } else {
                  totalSize += fs.statSync(filePath).size;
                }
              }
              return totalSize;
            };

            const buildSize = getDirectorySize('./dist');
            const buildSizeMB = (buildSize / 1024 / 1024).toFixed(2);

            const comment = `## 🚀 Preview Build Complete

            **Build Size:** ${buildSizeMB} MB
            **Status:** ✅ Build successful
            **Tests:** ✅ Passed

            The build completed successfully! Here's what was checked:
            - ✅ Dependencies installed
            - ✅ Tests passed
            - ✅ Build completed without errors
            - ✅ Build size within reasonable limits

            Once this PR is merged, it will be automatically deployed to production.`;

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: comment
            });

      - name: Upload Preview Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: preview-build-${{ github.event.number }}
          path: ./dist
          retention-days: 7
